name: ICESat2_cloud_access 
channels:
 - conda-forge
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - earthaccess=0.5.0
 - hvplot
 - xarray
