name: smap-tutorial
channels:
- conda-forge
dependencies:
- python=3.10
- jupyterlab
- earthaccess
- h5py
- xarray
- rioxarray
- h5netcdf
- dask
- matplotlib
- cartopy
- affine
- numpy<2.1

#- vaex
#- jupyter-offlinenotebook
#- sidecar
#- geoviews

- pipreqsnb
- conda-lock>=1.2.1
- mamba>=1.0
platforms:
- linux-64
- osx-64
- win-64
