name: nsidc-tutorial-icesat2-apps
channels:
- conda-forge
dependencies:
- python=3.12

- jupyterlab
#- jupyter_contrib_nbextensions

- earthaccess

- xarray
- rioxarray
- dask
- bottleneck
- h5py
- netcdf4
- h5netcdf
- libgdal-hdf4
- python-dateutil

- geopandas

- matplotlib
- cartopy

# For development
- nbdime

platforms:
- linux-64
- osx-64
- win-64
