name: nsidc-tutorials
channels:
- conda-forge
dependencies:
- python=3.9
- pangeo-notebook
- fsspec>=2022.10
- gdal=3.6
- numpy
- xarray
- matplotlib-base>=3.5
- ipyleaflet
- shapely
- geopandas
- h5py
- h5netcdf
- netcdf4~=1.6.2
- geopy
- pyresample
- earthaccess>=0.5.0
- fiona
- zarr
- ipympl
- descartes
- rasterio~=1.3.6
- plotly
- joblib
- cartopy
- pystac-client
- vaex
- intake-xarray
- intake-stac
- jupyter-offlinenotebook
- sidecar
- icepyx
- geoviews
- pipreqsnb
- conda-lock=1.2.1
- mamba>=1.0
- pip
platforms:
- linux-64
- osx-64
