name: nsidc-tutorials
channels:
- conda-forge
dependencies:
- python=3.9
- pangeo-notebook
- gdal=3.5
- xarray
- matplotlib-base
- ipyleaflet
- shapely
- geopandas
- h5py
- h5pyd
- h5netcdf
- netcdf4
- geopy
- pyresample
- earthaccess
- fiona
- zarr
- ipympl
- descartes
- rasterio
- plotly
- joblib
- cartopy
- pystac-client
- s3fs
- vaex
- tqdm
- intake-xarray
- intake-stac
- jupyter-offlinenotebook
- sidecar
- icepyx
- geoviews
- pipreqsnb
- conda-lock=1.2.1
- mamba>=1.0
- pip
platforms:
- linux-64
- osx-64
