name: nsidc-tutorials
channels:
- conda-forge
dependencies:
- python=3.9
- fsspec>=2022.10
- gdal=3.6
- xarray
- matplotlib-base>=3.5
- ipyleaflet
- shapely
- numpy=1.23.5 # datasharder bug
- geopandas
- h5py
- h5netcdf
- netcdf4=1.6.2
- geopy
- pyresample
- earthaccess>=0.6.1
- fiona
- zarr
- ipympl
- descartes
- rasterio~=1.3.6
- plotly
- joblib
- cartopy
- icepyx
- h5coro
- pystac-client
- vaex
- intake-xarray
- intake-stac
- jupyter-offlinenotebook
- sidecar
- geoviews
- pipreqsnb
- conda-lock>=1.2.1
- mamba>=1.0
- coiled>=0.9.30
- pip
- pip:
  - awscliv2
platforms:
- linux-64
- osx-64
- win-64
