name: Test Notebooks

on:
  pull_request:
    paths:
      - notebooks/**
      - binder/**
      - '.github/workflows/'
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: "Install Conda environment with Micromamba"
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-env: true
          environment-file: binder/conda-linux-64.lock
          environment-name: nsidc-tutorials

      - name: "Verify micromamba"
        shell: bash -l {0}
        run: |
          micromamba info
          jupyter kernelspec list
          which python
          conda list | sort

      - name: "Verify that libraries used in notebooks are present in the environment"
        shell: bash -l {0}
        run: |
          find notebooks -type f -iname \*.ipynb  -not -path '*\.ipynb_checkpoints/*' -not -path '*/iceflow/*'  | xargs -I % python .github/workflows/scan_notebooks.py -n %

      - name: "Setup Quarto"
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # version: 1.1.251
          version: 1.3.361

      - name: "Execute notebooks with Quarto"
        env:
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
        shell: bash -l {0}
        run: |
          find notebooks -type f -name "*.ipynb" -not -path '*\.ipynb_checkpoints/*' -not -path '*endered*' -not -path '*SnowEx*'  | xargs -I F quarto render "F" --execute --execute-daemon-restart


  win-osx:
    name: Runtime (${{ matrix.os }}, micromamba)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["windows", "macos"]
        include:
          - os: windows
            environment-file: binder/conda-win-64.lock
          - os: macos
            environment-file: binder/conda-osx-64.lock
    steps:
      - uses: actions/checkout@v3
      - name: "Install Conda environment with Micromamba"
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-env: true
          environment-file: ${{ matrix.environment-file }}
          environment-name: nsidc-tutorials

      - name: "Verify micromamba"
        shell: bash -l {0}
        run: |
          micromamba info
          jupyter kernelspec list
          printenv | sort
